/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class volador_demoffmpeg_NDKUtils */

#ifndef _Included_volador_demoffmpeg_NDKUtils
#define _Included_volador_demoffmpeg_NDKUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     volador_demoffmpeg_NDKUtils
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_volador_demoffmpeg_NDKUtils_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     volador_demoffmpeg_NDKUtils
 * Method:    studyLesson1
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_volador_demoffmpeg_NDKUtils_studyLesson1
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     volador_demoffmpeg_NDKUtils
 * Method:    studyLesson2
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_volador_demoffmpeg_NDKUtils_studyLesson2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     volador_demoffmpeg_NDKUtils
 * Method:    streamVideo
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_volador_demoffmpeg_NDKUtils_streamVideo
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     volador_demoffmpeg_NDKUtils
 * Method:    testEncodeYUVToH264
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_volador_demoffmpeg_NDKUtils_testEncodeYUVToH264
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     volador_demoffmpeg_NDKUtils
 * Method:    initFFMpeg
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_volador_demoffmpeg_NDKUtils_initFFMpeg
  (JNIEnv *, jobject, jstring);

/*
 * Class:     volador_demoffmpeg_NDKUtils
 * Method:    onPreviewFrame
 * Signature: ([BIII)I
 */
JNIEXPORT jint JNICALL Java_volador_demoffmpeg_NDKUtils_onPreviewFrame
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint);

/*
 * Class:     volador_demoffmpeg_NDKUtils
 * Method:    releaseFFMpeg
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_volador_demoffmpeg_NDKUtils_releaseFFMpeg
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
