/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class volador_demoffmpeg_FFMpegStreamer */

#ifndef _Included_volador_demoffmpeg_FFMpegStreamer
#define _Included_volador_demoffmpeg_FFMpegStreamer
#ifdef __cplusplus
extern "C" {
#endif
#undef volador_demoffmpeg_FFMpegStreamer_RAW_DATA_VIDEO
#define volador_demoffmpeg_FFMpegStreamer_RAW_DATA_VIDEO 1L
#undef volador_demoffmpeg_FFMpegStreamer_RAW_DATA_AUDIO
#define volador_demoffmpeg_FFMpegStreamer_RAW_DATA_AUDIO 2L
/*
 * Class:     volador_demoffmpeg_FFMpegStreamer
 * Method:    init
 * Signature: (Ljava/lang/String;IIIII)I
 */
JNIEXPORT jint JNICALL Java_volador_demoffmpeg_FFMpegStreamer_init
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint, jint);

/*
 * Class:     volador_demoffmpeg_FFMpegStreamer
 * Method:    prepair
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_volador_demoffmpeg_FFMpegStreamer_prepair
  (JNIEnv *, jobject);

/*
 * Class:     volador_demoffmpeg_FFMpegStreamer
 * Method:    encodeVideo
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_volador_demoffmpeg_FFMpegStreamer_encodeVideo
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     volador_demoffmpeg_FFMpegStreamer
 * Method:    encodeAudio
 * Signature: ([SI)I
 */
JNIEXPORT jint JNICALL Java_volador_demoffmpeg_FFMpegStreamer_encodeAudio
  (JNIEnv *, jobject, jshortArray, jint);

/*
 * Class:     volador_demoffmpeg_FFMpegStreamer
 * Method:    pause
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_volador_demoffmpeg_FFMpegStreamer_pause
  (JNIEnv *, jobject);

/*
 * Class:     volador_demoffmpeg_FFMpegStreamer
 * Method:    release
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_volador_demoffmpeg_FFMpegStreamer_release
  (JNIEnv *, jobject);

/*
 * Class:     volador_demoffmpeg_FFMpegStreamer
 * Method:    setLogPath
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_volador_demoffmpeg_FFMpegStreamer_setLogPath
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
