/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class volador_demoffmpeg_JNIMain */

#ifndef _Included_volador_demoffmpeg_JNIMain
#define _Included_volador_demoffmpeg_JNIMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     volador_demoffmpeg_JNIMain
 * Method:    main
 * Signature: (I[Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_volador_demoffmpeg_JNIMain_main
        (JNIEnv *env, jobject jo, jint argc, jobjectArray args);

#ifdef __cplusplus
}
#endif
#endif
